source 'https://rubygems.org'
gem "activerecord",'=4.2.6'
gem 'activerecord-jdbcmysql-adapter'
gem 'composite_primary_keys', '>8.0.0'
gem 'sinatra'
gem 'sinatra-contrib'
gem 'sinatra-activerecord'
gem 'rake'
gem 'activesupport'
gem 'rest-client'
gem 'redis'
gem 'puma'
gem 'jwt'
gem 'celluloid'
gem "march_hare", "~> 3.0"
gem "arangorb"