development:
  adapter: jdbcmysql
  host: 192.168.42.11
  database: metadata
  username: vagrant
  password: vagrant
  pool: 10
  timeout: 20000

staging:
  adapter: jdbcmysql
  host: 192.99.147.128
  database: metadata
  username: metaserver
  password: metaserver
  pool: 10
  timeout: 30000

production:
  adapter: jdbcmysql
  host: 10.0.3.1
  database: metadata
  username: metaserver
  password: metaserver
  pool: 10
  timeout: 30000


