require_relative 'src/tables/views'
require_relative 'src/tables/parts'
require_relative 'src/attr_readers/where_used_attr_reader'
require_relative 'src/attr_readers/composit_attrs_reader'
require_relative 'src/attr_readers/price_attr_reader'
require_relative 'src/decriptor'