development:
  adapter: jdbcmysql
  host: 192.99.147.128
  database: metadata
  username: metaserver
  password: metaserver
  pool: 5
  timeout: 5000

staging:
  adapter: jdbcmysql
  host: 10.0.3.1
  database: metadata
  username: metaserver
  password: metaserver
  pool: 20
  timeout: 5000

production:
  adapter: jdbcmysql
  host: 10.0.3.1
  database: metadata
  username: metaserver
  password: metaserver
  pool: 5
  timeout: 5000


